// Code generated by github.com/sllt/kite/cli/kite. DO NOT EDIT.
// versions:
// 	kite-cli v0.7.0
// 	github.com/sllt/kite v1.39.0
// 	source: hello.proto

package server

import (
	"context"
	"time"
	
	"github.com/sllt/kite/pkg/kite"
	"github.com/sllt/kite/pkg/kite/infra"
	kitegRPC "github.com/sllt/kite/pkg/kite/grpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	
	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewHelloKiteServer creates a new instance of HelloKiteServer
func NewHelloKiteServer() *HelloKiteServer {
	return &HelloKiteServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// HelloServerWithKite is the interface for the server implementation
type HelloServerWithKite interface {
	SayHello(*kite.Context) (any, error)
}

// HelloServerWrapper wraps the server and handles request and response logic
type HelloServerWrapper struct {
	HelloServer
	*healthServer
	Container *infra.Container
	server    HelloServerWithKite
}

// Base instrumented stream
type instrumentedStream struct {
	grpc.ServerStream
	ctx    *kite.Context
	method string
}

func (s *instrumentedStream) Context() context.Context {
	return s.ctx
}

func (s *instrumentedStream) SendMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/SendMsg")
	defer span.End()

	err := s.ServerStream.SendMsg(m)

	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/SendMsg", "app_gRPC-Stream_stats")

	return err
}

func (s *instrumentedStream) RecvMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/RecvMsg")
	defer span.End()

	err := s.ServerStream.RecvMsg(m)

	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/RecvMsg", "app_gRPC-Stream_stats")

	return err
}



// Unary method handler for SayHello
func (h *HelloServerWrapper) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	gctx := h.getKiteContext(ctx, &HelloRequestWrapper{ctx: ctx, HelloRequest: req})
	
	res, err := h.server.SayHello(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*HelloResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}
	
	return resp, nil
}

// mustEmbedUnimplementedHelloServer ensures implementation
func (h *HelloServerWrapper) mustEmbedUnimplementedHelloServer() {}

// RegisterHelloServerWithKite registers the server
func RegisterHelloServerWithKite(app *kite.App, srv HelloServerWithKite) {
	registerServerWithKite(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &HelloServerWrapper{
			server: srv.(HelloServerWithKite),
			healthServer: getOrCreateHealthServer(),
		}

		RegisterHelloServer(s, wrapper)

		wrapper.Server.SetServingStatus("Hello", healthpb.HealthCheckResponse_SERVING)
	})
}

// getKiteContext creates Kite context
func (h *HelloServerWrapper) getKiteContext(ctx context.Context, req kite.Request) *kite.Context {
	return &kite.Context{
		Context:   ctx,
		Container: h.Container,
		Request:   req,
	}
}
