// Code generated by github.com/sllt/kite/cli/kite. DO NOT EDIT.
// versions:
// 	kite-cli v0.7.0
// 	github.com/sllt/kite v1.39.0
// 	source: chat.proto

package client

import (
	"github.com/sllt/kite/pkg/kite"
	"github.com/sllt/kite/pkg/kite/metrics"
	"google.golang.org/grpc"
)

type ChatServiceKiteClient interface {
	ServerStream(ctx *kite.Context, req *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	ClientStream(ctx *kite.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error)
	BiDiStream(ctx *kite.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
	HealthClient
}

type ChatServiceClientWrapper struct {
	client ChatServiceClient
	HealthClient
}

func NewChatServiceKiteClient(host string, metrics metrics.Manager, dialOptions ...grpc.DialOption) (ChatServiceKiteClient, error) {
	conn, err := createGRPCConn(host, "ChatService", dialOptions...)
	if err != nil {
		return &ChatServiceClientWrapper{
			client:       nil,
			HealthClient: &HealthClientWrapper{client: nil},
		}, err
	}

	metricsOnce.Do(func() {
		metrics.NewHistogram("app_gRPC-Client_stats", "Response time of gRPC client in milliseconds.", gRPCBuckets...)
		metrics.NewHistogram("app_gRPC-Client-Stream_stats", "Response time of gRPC streaming client in milliseconds.", gRPCBuckets...)
	})

	res := NewChatServiceClient(conn)
	healthClient := NewHealthClient(conn)

	return &ChatServiceClientWrapper{
		client: res,
		HealthClient: healthClient,
	}, nil
}


func (h *ChatServiceClientWrapper) ServerStream(ctx *kite.Context, req *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	result, err := invokeRPC(ctx, "/ChatService/ServerStream", func() (interface{}, error) {
		return h.client.ServerStream(ctx.Context, req, opts...)
	}, "app_gRPC-Client-Stream_stats")

	if err != nil {
		return nil, err
	}
	return result.(grpc.ServerStreamingClient[Response]), nil
}
func (h *ChatServiceClientWrapper) ClientStream(ctx *kite.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Request, Response], error) {
	result, err := invokeRPC(ctx, "/ChatService/ClientStream", func() (interface{}, error) {
		return h.client.ClientStream(ctx.Context, opts...)
	}, "app_gRPC-Client-Stream_stats")

	if err != nil {
		return nil, err
	}
	return result.(grpc.ClientStreamingClient[Request, Response]), nil
}
func (h *ChatServiceClientWrapper) BiDiStream(ctx *kite.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	result, err := invokeRPC(ctx, "/ChatService/BiDiStream", func() (interface{}, error) {
		return h.client.BiDiStream(ctx.Context, opts...)
	}, "app_gRPC-Client-Stream_stats")

	if err != nil {
		return nil, err
	}
	return result.(grpc.BidiStreamingClient[Request, Response]), nil
}
