// Code generated by github.com/sllt/kite/cli/kite. DO NOT EDIT.
// versions:
// 	kite-cli v0.7.0
// 	github.com/sllt/kite v1.39.0
// 	source: hello.proto

package client

import (
	"github.com/sllt/kite/pkg/kite"
	"github.com/sllt/kite/pkg/kite/metrics"
	"google.golang.org/grpc"
)

type HelloKiteClient interface {
	SayHello(ctx *kite.Context, req *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	HealthClient
}

type HelloClientWrapper struct {
	client HelloClient
	HealthClient
}

func NewHelloKiteClient(host string, metrics metrics.Manager, dialOptions ...grpc.DialOption) (HelloKiteClient, error) {
	conn, err := createGRPCConn(host, "Hello", dialOptions...)
	if err != nil {
		return &HelloClientWrapper{
			client:       nil,
			HealthClient: &HealthClientWrapper{client: nil},
		}, err
	}

	metricsOnce.Do(func() {
		metrics.NewHistogram("app_gRPC-Client_stats", "Response time of gRPC client in milliseconds.", gRPCBuckets...)
	})

	res := NewHelloClient(conn)
	healthClient := NewHealthClient(conn)

	return &HelloClientWrapper{
		client: res,
		HealthClient: healthClient,
	}, nil
}


func (h *HelloClientWrapper) SayHello(ctx *kite.Context, req *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	result, err := invokeRPC(ctx, "/Hello/SayHello", func() (interface{}, error) {
		return h.client.SayHello(ctx.Context, req, opts...)
	}, "app_gRPC-Client_stats")

	if err != nil {
		return nil, err
	}
	return result.(*HelloResponse), nil
}
