// Code generated by github.com/sllt/kite/cli/kite. DO NOT EDIT.
// versions:
// 	kite-cli v0.7.0
// 	github.com/sllt/kite v1.39.0
// 	source: chat.proto

package server

import (
	"context"
	"time"
	
	"github.com/sllt/kite/pkg/kite"
	"github.com/sllt/kite/pkg/kite/infra"
	kitegRPC "github.com/sllt/kite/pkg/kite/grpc"
	"google.golang.org/grpc"
	
	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewChatServiceKiteServer creates a new instance of ChatServiceKiteServer
func NewChatServiceKiteServer() *ChatServiceKiteServer {
	return &ChatServiceKiteServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// ChatServiceServerWithKite is the interface for the server implementation
type ChatServiceServerWithKite interface {
	ServerStream(*kite.Context, ChatService_ServerStreamServer) error
	ClientStream(*kite.Context, ChatService_ClientStreamServer) error
	BiDiStream(*kite.Context, ChatService_BiDiStreamServer) error
}

// ChatServiceServerWrapper wraps the server and handles request and response logic
type ChatServiceServerWrapper struct {
	ChatServiceServer
	*healthServer
	Container *infra.Container
	server    ChatServiceServerWithKite
}

// Base instrumented stream
type instrumentedStream struct {
	grpc.ServerStream
	ctx    *kite.Context
	method string
}

func (s *instrumentedStream) Context() context.Context {
	return s.ctx
}

func (s *instrumentedStream) SendMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/SendMsg")
	defer span.End()

	err := s.ServerStream.SendMsg(m)

	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/SendMsg", "app_gRPC-Stream_stats")

	return err
}

func (s *instrumentedStream) RecvMsg(m interface{}) error {
	start := time.Now()
	span := s.ctx.Trace(s.method + "/RecvMsg")
	defer span.End()

	err := s.ServerStream.RecvMsg(m)

	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(s.ctx, s.ctx.Logger, s.ctx.Metrics(), start, err,
		s.method+"/RecvMsg", "app_gRPC-Stream_stats")

	return err
}

// Server-side streaming specific wrapper
type serverStreamWrapperServerStream struct {
	*instrumentedStream
}

func (w *serverStreamWrapperServerStream) Send(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Send")
	defer span.End()
	
	err := w.ServerStream.SendMsg(m)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/Send", "app_gRPC-Stream_stats")
	
	return err
}
// Client-side streaming specific wrapper
type clientStreamWrapperClientStream struct {
	*instrumentedStream
}

func (w *clientStreamWrapperClientStream) SendAndClose(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/SendAndClose")
	defer span.End()
	
	err := w.ServerStream.SendMsg(m)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/SendAndClose", "app_gRPC-Stream_stats")
	
	return err
}

func (w *clientStreamWrapperClientStream) Recv() (*Request, error) {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Recv")
	defer span.End()
	
	var req Request
	err := w.ServerStream.RecvMsg(&req)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/Recv", "app_gRPC-Stream_stats")
	
	return &req, err
}
// Client-side streaming specific wrapper
type clientStreamWrapperBiDiStream struct {
	*instrumentedStream
}

func (w *clientStreamWrapperBiDiStream) SendAndClose(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/SendAndClose")
	defer span.End()
	
	err := w.ServerStream.SendMsg(m)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/SendAndClose", "app_gRPC-Stream_stats")
	
	return err
}

func (w *clientStreamWrapperBiDiStream) Recv() (*Request, error) {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Recv")
	defer span.End()
	
	var req Request
	err := w.ServerStream.RecvMsg(&req)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/Recv", "app_gRPC-Stream_stats")
	
	return &req, err
}
// Bidirectional streaming wrapper
type bidiStreamWrapperBiDiStream struct {
	*instrumentedStream
}

func (w *bidiStreamWrapperBiDiStream) Send(m *Response) error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Send")
	defer span.End()
	
	err := w.ServerStream.SendMsg(m)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/Send", "app_gRPC-Stream_stats")
	
	return err
}

func (w *bidiStreamWrapperBiDiStream) Recv() (*Request, error) {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/Recv")
	defer span.End()
	
	var req Request
	err := w.ServerStream.RecvMsg(&req)
	
	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
	w.method+"/Recv", "app_gRPC-Stream_stats")
	
	return &req, err
}

func (w *bidiStreamWrapperBiDiStream) CloseSend() error {
	start := time.Now()
	span := w.ctx.Trace(w.method + "/CloseSend")
	defer span.End()

	err := w.ServerStream.(grpc.ClientStream).CloseSend()

	logger := kitegRPC.NewgRPCLogger()
	logger.DocumentRPCLog(w.ctx, w.ctx.Logger, w.ctx.Metrics(), start, err,
		w.method+"/CloseSend", "app_gRPC-Stream_stats")

	return err
}


// Server-side streaming handler for ServerStream
func (h *ChatServiceServerWrapper) ServerStream(req *Request, stream ChatService_ServerStreamServer) error {
	ctx := stream.Context()
	gctx := h.getKiteContext(ctx, &RequestWrapper{ctx: ctx, Request: req})
	
	is := &instrumentedStream{
		ServerStream: stream,
		ctx:        gctx,
		method:     "/ChatService/ServerStream",
	}
	
	wrappedStream := &serverStreamWrapperServerStream{instrumentedStream: is}
	return h.server.ServerStream(gctx, wrappedStream)
}
// Client-side streaming handler for ClientStream
func (h *ChatServiceServerWrapper) ClientStream(stream ChatService_ClientStreamServer) error {
	ctx := stream.Context()
	gctx := h.getKiteContext(ctx, nil)
	
	is := &instrumentedStream{
		ServerStream: stream,
		ctx:        gctx,
		method:     "/ChatService/ClientStream",
	}
	
	wrappedStream := &clientStreamWrapperClientStream{instrumentedStream: is}
	return h.server.ClientStream(gctx, wrappedStream)
}
// Bidirectional streaming handler for BiDiStream
func (h *ChatServiceServerWrapper) BiDiStream(stream ChatService_BiDiStreamServer) error {
	ctx := stream.Context()
	gctx := h.getKiteContext(ctx, nil)
	
	is := &instrumentedStream{
		ServerStream: stream,
		ctx:        gctx,
		method:     "/ChatService/BiDiStream",
	}
	
	wrappedStream := &bidiStreamWrapperBiDiStream{instrumentedStream: is}
	return h.server.BiDiStream(gctx, wrappedStream)
}

// mustEmbedUnimplementedChatServiceServer ensures implementation
func (h *ChatServiceServerWrapper) mustEmbedUnimplementedChatServiceServer() {}

// RegisterChatServiceServerWithKite registers the server
func RegisterChatServiceServerWithKite(app *kite.App, srv ChatServiceServerWithKite) {
	registerServerWithKite(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &ChatServiceServerWrapper{
			server: srv.(ChatServiceServerWithKite),
			healthServer: getOrCreateHealthServer(),
		}

		RegisterChatServiceServer(s, wrapper)

		wrapper.Server.SetServingStatus("Hello", healthpb.HealthCheckResponse_SERVING)
	})
}

// getKiteContext creates Kite context
func (h *ChatServiceServerWrapper) getKiteContext(ctx context.Context, req kite.Request) *kite.Context {
	return &kite.Context{
		Context:   ctx,
		Container: h.Container,
		Request:   req,
	}
}
